### ISSUE TITLE
Facebook Connect 

### ISSUE THREAD

**Issue by mrburriss** [moxi9/phpfox-v3-dist#1]
Phpfox issue with facebook on laptop. here is error message 

Invalid Scopes: publish_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

Please fix i am not able to get in my site at all.

Thanks

**Comment by raymondseow** [comment]
i have also reported similar problem no help at all

**Comment by mrburriss** [comment]
Wht do we do? I am the one losing out.
Download "Got Swag?" the app right now!
On Jun 15, 2015 12:18 AM, raymondseow <notifications@github.com> wrote:i have also reported similar problem no help at all

**Comment by Anna3anana** [comment]
Hello,

1. Could you please tell us how you got the error?
2. What browser and what version are you using?
3. What OS are you running?
4. Have you tried this on other browser's and is it not work there either?
5. Do you have a printscreen of this?
6. What is your PHPfox version (please note that if you are not running the latest version we will kindly have to ask you to upgrade to v3.8)?

I look forward hearing from you. Thanks.

**Comment by leeboe89** [comment]
1. I get the error if I try to log into the site using facebook log-in
2. Latest Chrome
3. My OS is Win 8.1
4. Yes and No same issue
5. yes at bottom of this list
6. I am using v3.80 (build 1)
 ![image](https://cloud.githubusercontent.com/assets/975007/8452548/cecb5b68-1fb9-11e5-81f9-845ce93b14df.png)

**Comment by mrburriss** [comment]
1. Now when I enable Facebook Connect it doesnt even show up on site to connect to Facebook. 
2.I am using Chrome
3.So Now that i am not able to enable facebook i cannot show u printscreen.
4. I just paid for social connect and it is not uploaded yet.
5. will the upgrade fix the issue for facebook and uploading videos?
6. this is a tedious process trying to fix an issue on your end.
 
Octavius Burriss, CEO
Swagovaload Entertainment
Get the App.    Got Swag?
"The fastest growing entertainment community"
704.516.3984
www.swagovaload.com
www.facebook.com/4swag
theboss@swagovaload.com

CONFIDENTIALITY NOTICE: This e-mail transmission, and any documents, files or previous email messages attached to it may contain confidential information that is legally privileged. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this transmission is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify the sender. Please destroy the original transmission and its attachments without reading or saving in any manner.
 
 
--------- Original Message --------- Subject: Re: [phpfox-v3-dist] Facebook Connect (#1)

**Comment by mrburriss** [comment]
I have sent this error 1000 times. facebook connect doesnt work.
 
Octavius Burriss, CEO
Swagovaload Entertainment
Get the App.    Got Swag?
"The fastest growing entertainment community"
704.516.3984
www.swagovaload.com
www.facebook.com/4swag
theboss@swagovaload.com

CONFIDENTIALITY NOTICE: This e-mail transmission, and any documents, files or previous email messages attached to it may contain confidential information that is legally privileged. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this transmission is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify the sender. Please destroy the original transmission and its attachments without reading or saving in any manner.
 
 
--------- Original Message --------- Subject: Re: [phpfox-v3-dist] Facebook Connect (#1)

**Comment by Data66PF** [comment]
If you log in to view this tutorial, http://scripttechs.com/article/353/fix-facebook-publish_stream-error/ it has a fix for this publish_stream error. You need to upload a profile pic on my site in order to automatically be in the verified user group to see tutorials.

**Comment by Data66PF** [comment]
I wrote a tutorial for a source edit to fix this but this is a bug with outdated code. http://scripttechs.com/article/353/fix-facebook-publish_stream-error/

**Comment by RaymondBenc** [comment]
Fixed in 3.9.
