### ISSUE TITLE
Blank White Pages, for Ad Management,

### ISSUE THREAD

**Issue by crashgear** [moxi9/phpfox-v3-dist#10]
So I have fixed this one before last yr as a matter fact BUT on a rebuild it Haunted me again. There is something calling those pages some of the Sub Mods work and some don't this simply being in the ad management and creation. 
This does affect other areas BUT I know I have dealt with and defeated this bugger. I was simply not smart enough to write it down and a solution. 
It basically gives me a Blank White page with NO errors I inspect the element and NOTTA shows up, I have run Debug and gotten NOTTA. I'm still VERY Partial to 3.8 Latest NOT ready of comfortable for 4 yet.. 

As I said there is NO error it simply calls a Blank Page.. So I am thinking it is NOT being called at all. I believe the page calling it is not stable. I did fix this last year BUT I am not sure HOW..

Can anyone Please tell me what page is calling the ad module...... 

TY in Advance,

**Comment by Data66PF** [comment]
Cannot reproduce. Please note that questions about issues need to be raised in the forum as this is only for bugs.

**Comment by crashgear** [comment]
That is a bug, how else would you describe it either way it is a bug..

**Comment by crashgear** [comment]
It also does that on my Dev site as well. So this is surely a bug and not an error on the server...

**Comment by crashgear** [comment]
The First Working one is for adding BUT you cannot add an Image as that is PART of the Bug I know I've fixed it BUT I cannot FIND what I did. The second one is the bad one. No errors etc I simply need to know WHAT main Function page Calls those.. its like the 2-3-4-6 dont work right on the ad mods.. These are from my Dev not Prod SAME issue though..


![screenhunter_44 jan 10 12 23](https://cloud.githubusercontent.com/assets/16635705/12223455/364581d8-b795-11e5-96bd-0d300aedaa92.jpg)
![screenhunter_43 jan 10 12 22](https://cloud.githubusercontent.com/assets/16635705/12223456/37aa50c6-b795-11e5-8ea7-042942e5d22b.jpg)

**Comment by Data66PF** [comment]
If it were a bug, it would not work on any of my sites which are on three different types of servers and other clients would have reported it. You are the only one reporting it. 
I can go to the ad module and click Create New Campaign. It goes to a page that shows like your second image, which appears to be working. 
I can select an image and load it and the ad works. 
Please note that you are breaking the license terms with that development site. The terms require it to be in a phpfoxdev or development subfolder or subdomain. Please fix that in order to conform to the license terms.

**Comment by Data66PF** [comment]
I've tested this on local test sites, live test sites and live sites. I cannot reproduce any issue with creating or managing ads. Please be sure you have the latest version of v3.8 and that your server is updated to support it with the current requirements. Note that mod_sec can need tweaks for admin functions if using that on your server. Also open_basedir can cause issues if that is enabled.
