### ISSUE TITLE
attachment files are not being deleted once member deletes content.

### ISSUE THREAD

**Issue by cybervang** [moxi9/phpfox-v3-dist#11]
There is a big issue with old files that are left over when members delete their content & the attachment directory using only 1 directory.
Attachment/YEAR/1 <-----

Many hosts do not allow a certain amount of files in "1" directory and so large sites will have issues
when it hits an X amount of files per dir. Also will cause performance issues.

phpfox uses DATES as directory and so LARGE sites will get hit by this limitation since thousands of files get generated fast before a day goes by or a year. It isn't the size per file that is the issue but more the X amount of files per dir.

Size matters too if it isn't deleted if left overs build up on large sites and will cause performance issues over time.

Needs this fixed otherwise admin will have to constantly delete & monitor those unused files.
Admin will also have to monitor the directory file counts and making sure it's not beyond the host's limits.

There needs a better method of storing files & deleting unused files. Content that is deleted should delete it's attachments and any media belonging to it upon deletion.

**Comment by RaymondBenc** [comment]
This requires a lot of changes to how the system works with v3 and v4. We have moved this to our internal tracker to be implemented in v4.
