### ISSUE TITLE
ATTACHMENTS are displaying "PLAY" in feed.

### ISSUE THREAD

**Issue by cybervang** [moxi9/phpfox-v3-dist#12]
I am using V3.8.
Tested this on all default template.

When you post a blog, the output is displaying the word "PLAY".

You have to manually delete that word from the BLOG text in database to fix it.
![attachbug_1](https://cloud.githubusercontent.com/assets/16280954/12406685/f41acb0c-be14-11e5-89b9-4bd7ca5cce53.png)

![attachbug_2](https://cloud.githubusercontent.com/assets/16280954/12406687/f41cdb54-be14-11e5-8811-b5e7cf108dce.png)

![attachbug_3](https://cloud.githubusercontent.com/assets/16280954/12406686/f41c8f00-be14-11e5-9808-6adff96b1504.png)

![attachbug_4](https://cloud.githubusercontent.com/assets/16280954/12406684/f419d8be-be14-11e5-9dcc-e02136c66e05.png)

**Comment by Data66PF** [comment]
Please provide a screen shot. What version are you using? What os and browser? I cannot reproduce this in my 3.8.0 build 1 site on chrome with macbook. Using default feed and theme. No source edits as this is a vanilla install. Please provide all  details for testing, including what attachment you are putting on the blog and if it is inline or regular.

**Comment by RaymondBenc** [comment]
We were able to reproduce the issues you were having, however due to a setting that strips out all HTML, this also strips out the Play links. This is the reason why you just get the word Play. This is something we cannot enhance in v3, but we are looking at better ways to display attachments in v4.
