### ISSUE TITLE
Phppfox can not support facebook video anymore?

### ISSUE THREAD

**Issue by juniortimeline** [moxi9/phpfox-v3-dist#13]
Hi Good Day,

Since I install my phpfox 3.8.8. My site is not support facebook video using PASTE URL. I receive an error message "Unable to embed this video due to privacy settings." and also video embed from facebook is not support and share facebook url on feed. I hope someone can solved this problem. Thank You!

**Comment by RaymondBenc** [comment]
Facebook video embedding is currently not supported in v3, however we have added a new routine for 4.3.
