### ISSUE TITLE
TinyMCE loading everywhere regardless of settings

### ISSUE THREAD

**Issue by KStenvall** [moxi9/phpfox-v3-dist#14]
In the current 3.8 version of phpFox, if TinyMCE is selected as the WYSIWYG editor it loads everywhere regardless of the settings in AdminCP > Load TinyMCE on Controllers.

On the pages where it should not load my browser inspector shows the following error:

Uncaught ReferenceError: Editor is not defined
Loading TinyMCE for: text (common.js:50)

This is on a fresh install - no add-ons or 3rd-party themes.

_This was a bug in an earlier version and has returned._

**Comment by cybervang** [comment]
Hmm, I'll see if I get the same thing. I never realize this but if that's the case it's going to cause issues for add ons or pages that NEEDING TINYMce since it's just a small text editor for a small purpose.
Testing now.
