### ISSUE TITLE
Blogs don't keep privacy settings.

### ISSUE THREAD

**Issue by frozenfire98** [moxi9/phpfox-v3-dist#15]
This one is more irritating than anything else and not supremely important in the grand scheme of things, but thought I'd post it in case it's a quick fix :)

When you create a blog, you set your permissions there as to who can view/comment. You post it, and then if you go back in, it didn't save them.

You have to re-set the permissions, and it seems to stick the 2nd time around.

**Comment by Data66PF** [comment]
From our core devs, this is working in v4 and is not an issue we'll be fixing in v3.8. As this function works without issues in v4, please upgrade to have the fix.
