### ISSUE TITLE
Screen goes blank when uploading youtube videos phpfox3

### ISSUE THREAD

**Issue by broocp** [moxi9/phpfox-v3-dist#2]
I get a blank screen when i attempt to upload youtube video. I am running php fox 3

**Comment by RaymondBenc** [comment]
The latest build https://github.com/moxi9/phpfox-v3-dist/commit/d5bd44dd5df284c3c5d92220ae0f5a82faa8667c has a fix that should resolve the issue you are having

**Comment by Data66PF** [comment]
This fix has made it so links can't be shared. http://community.phpfox.com/forum/thread/52401/please-help-can-039-t-load-link-content-in-new-feed/ throws an error. Confirmed on my new local install.
