### ISSUE TITLE
Pages/Group Issues

### ISSUE THREAD

**Issue by frozenfire98** [moxi9/phpfox-v3-dist#4]
We have had issues regarding page/group privacy and I've been consistently told that it's something I personally did, or working as designed. However, there are now more than me, and Data66 herself has verified that this is a bug. Now can we have some serious attention to this issue that affects every single site, please?

http://scripttechs.com/forum/thread/2429/news-feed-posts-in-pages/

http://scripttechs.com/forum/thread/2430/pages-groups-issues-and-question/

Problem- When a user posts in a page/group, the privacy DOES NOT WORK and the main feed shows it to their friends. No matter what the page/group privacy level is, when it posts in the feed, the privacy is broken.

You CAN post as the page/group itself OR go to your profile to delete the feed from your profile, but a, only admins can post as the page/group itself so that doesn't work for the majority. B, it's unfair to ask people to delete the feeds from their profiles that are meant to be a quick recap of their activity on the site. And C, this doesn't work for photos, so no matter how you post a personal, private photo in a personal, private group, it will spill into the feed for anyone to see who is on that person's friends list, and if you delete the feed from your profile, the post in the group goes as well.

I'd really love a fix for this. And would personally donate what I could towards the man-hours that would go towards fixing this as this is a HUGE aspect for social networking sites that needs to work properly. Heck, I will even personally allow for testing of patches on my site, provided they are tested on a dev site beforehand so they won't crash it. My users and I are that desperate for a fix, we're willing to be guinea pigs.

**Comment by Data66PF** [comment]
I'm unable to confirm bugs in this tracker yet but I can confirm this is a bug that was in the 3.8 issue tracker before. this bug mainly impacts large active sites but I also was able to see it on my ScriptTechs site when I had pages active. Note that the sites are NOT friends only community but the privacy should not be determined only by friends only community, a private page should be private whether a friends only community or not. Thanks!

**Comment by Data66PF** [comment]
Patch applied to the site.

**Comment by Data66PF** [comment]
needs more testing

**Comment by Data66PF** [comment]
fixed
