### ISSUE TITLE
Feeds disapppear in various ways.

### ISSUE THREAD

**Issue by frozenfire98** [moxi9/phpfox-v3-dist#5]
When a user comments on a friend's profile, the posts on their profile disappear. If they then go back to their own profile, their page is empty. They have to post a new status on their own profile in order to get those feeds back.

If a status with a link in it has more than 10 comments, it will throw an error and take you to the error page saying that the status cannot be found. The only way to workaround this is to post the link as the first comment, which no one likes because it doesn't show a preview of whatever we were linking to.

Sometimes feeds on a profile randomly completely disappear and it shows only a few, or something from every few days and leaves big gaping holes in the things that were posted. After a few days, whenever cache rotates or something, the posts show again, but they disappear soon after until the next cache rotation. This is very very frustrating for users who are afraid they're losing all of their posts and writing.

**Comment by Data66PF** [comment]
I have seen this on large, active sites. Note that it impacts sites that have very, very active feeds. It will take testing on the client's servers.

**Comment by RaymondBenc** [comment]
Patch. Open file: /module/feed/include/service/callback.class.php

Look for and remove:
```
if($aItem['user_id'] == Phpfox::getService('profile')->getProfileUserId())
{
	return false;
}
```

**Comment by frozenfire98** [comment]
It appears the patch for this has caused another bug, which is also on V4. Posting without refreshing the entire page makes the post disappear automatically.

**Comment by Lovinity** [comment]
Any developments since this bug was reported? We too are having the same issues with randomly disappearing statuses and feeds, and our users are very upset about it.

**Comment by frozenfire98** [comment]
Not yet, unfortunately. My users are pretty fed up as well, but the Fox team is using my site as a guinea pig to hopefully find answers for all of us.

**Comment by Lovinity** [comment]
Rats. It just deleted a status by a user who is suffering from depression and asking his friends for help, leaving a bad image in the user's eyes thinking staff deleted them. I'm forced to modify our code.
