### ISSUE TITLE
Hyperlink parsing isn't working correctly.

### ISSUE THREAD

**Issue by frozenfire98** [moxi9/phpfox-v3-dist#6]
Posting a link first does not turn it into a hyperlink. You must add text before it in order to have the site automatically turn the link text into a hyperlink.

Surely there is a way to make the links turn to hyperlinks regardless of if there is text posted before it or not?

**Comment by Data66PF** [comment]
I can confirm this even on the PHPfox community and on my own site so this one is for v3 and v4.

**Comment by RaymondBenc** [comment]
Patch... Open file: include/library/phpfox/parse/output.class.php

Look for:
```
$sTxt = $this->parseUrls($sTxt);
```

Above that add:
```
$sTxt =  ' ' . $sTxt;
```
