### ISSUE TITLE
Relationship Module Bug

### ISSUE THREAD

**Issue by frozenfire98** [moxi9/phpfox-v3-dist#9]
We're having an odd issue where relationships that have been confirmed for months will suddenly disappear off of the profiles and need to be completely redone.

That, or they go to edit something in their profile and see they're randomly in a relationship with someone they don't know and don't have on their friends list. It was never confirmed or anything, just a very weird bug, either it's disappearing when it shouldn't or it's appearing when it shouldn't. :)

**Comment by RaymondBenc** [comment]
We've been testing this for the last 2 days and was not able to reproduce it in v3. We are keeping an eye out for this issue in v4.
